### ISSUE TITLE
"Illegal instruction: 4" when running with output_file

### ISSUE THREAD

**Issue by noahsark769** [woshiccm/Pecker#25]
With the following `.pecker.yml`:

```yaml
reporter: "json"

disabled_rules:
  - skip_public
  
excluded: # paths to ignore during detecting. Takes precedence over `included`.
  - Carthage
  - Pods

blacklist_symbols: # symbols to ignore during detecting, contains class, struct, enum, etc.
  - AppDelegate
  - viewDidLoad

output_file: "./peckerout"
```

I get an illegal instruction when running pecker on [CIFilter.io](https://github.com/noahsark769/cifilter.io):

```
$ BUILD_ROOT=~/Library/Developer/Xcode/DerivedData/CIFilter.io-hibrtvbjsqlofacdruluolzdaqib/Index/DataStore/ pecker ./
Illegal instruction: 4
```

If I remove the `output_file` line, the script runs correctly.
